name: Deploy Lambda codes

on:
  push:
    branches: 
      - lambda/test

jobs:
  Deploy-Codes:
    runs-on: ubuntu-latest
    
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Zip index.js
        uses: NotCoffee418/s3-zip-upload@v1.1
        env:
          AWS_SECRET_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET_NAME: edgar-test-function-s3-bucket
          AWS_REGION: 'ap-southeast-1'
          SOURCE_MODE: ZIP
          SOURCE_PATH: ./code_repo/
          DEST_FILE: lambda_function_payload.zip

      - name: Update Lambda
        run: |
          aws lambda update-function-code \
          --function-name edgar-test-function \
          --s3-bucket edgar-test-function-s3-bucket \
          --s3-key lambda_function_payload.zip