name: Deploy Lambda codes

on:
  push:
    branches: 
      - lambda/test

jobs:
  Deploy-Codes:
    runs-on: ubuntu-latest
    
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Zip index.js
        uses: NotCoffee418/s3-zip-upload@v1.1
        env:
          AWS_SECRET_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET_NAME: edgar-test-function-s3-bucket
          AWS_REGION: 'ap-southeast-1'
          SOURCE_MODE: ZIP
          SOURCE_PATH: ./code_repo/
          DEST_FILE: lambda_function_payload.zip
    
      - name: Update Lambda
        uses: appleboy/lambda-action@v0.1.9
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: 'ap-southeast-1'
          function_name: edgar-test-function
          s3_bucket: edgar-test-function-s3-bucket